### ISSUE TITLE
Add option to avoid setting current image again

### ISSUE THREAD

**Issue by fvictorio** [gillchristian/wallp#2]
It would be awesome to have an option to instruct `wallp` to avoid setting the current wallpaper again. That way you'd be sure that calling `wallp` will change the image (unless you only have one image in your directory, then it should emit a warning or something).

I don't know how to name that flag. Maybe `wallp [-u|--unique]`?

**Comment by gillchristian** [comment]
Just added it. It works by default though, no flags are necessary.
